backend:
  name: github
  repo: dysicreator/topailists-site
  branch: main
  auth_scope: repo
  base_url: https://api.netlify.com
  auth_endpoint: auth
  app_id: CLIENT_ID_HERE

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Articles"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
